/**
 * Code Tools - Code Generation and Analysis Helpers
 */

const FileTools = require('./fileTools');

class CodeTools {
  constructor() {
    this.fileTools = new FileTools();
  }

  /**
   * Generate a simple website
   * @param {Object} spec - Website specification
   */
  async generateWebsite(spec) {
    const { pages = 6, title = 'My Website', theme = 'modern' } = spec;
    
    const files = [];

    // Generate index.html
    const indexHtml = this.generateIndexHtml(title, pages);
    await this.fileTools.createFile('index.html', indexHtml);
    files.push('index.html');

    // Generate style.css
    const css = this.generateCSS(theme);
    await this.fileTools.createFile('style.css', css);
    files.push('style.css');

    // Generate additional pages
    for (let i = 2; i <= pages; i++) {
      const pageName = `page${i}.html`;
      const pageHtml = this.generatePageHtml(`Page ${i}`, i, pages);
      await this.fileTools.createFile(pageName, pageHtml);
      files.push(pageName);
    }

    return {
      success: true,
      files,
      message: `Generated ${pages}-page website at ${this.fileTools.getWorkspacePath()}`
    };
  }

  /**
   * Generate index.html
   */
  generateIndexHtml(title, pageCount) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <nav>
        <h1>${title}</h1>
        <ul>
            <li><a href="index.html">Home</a></li>
            ${Array.from({ length: pageCount - 1 }, (_, i) => 
              `<li><a href="page${i + 2}.html">Page ${i + 2}</a></li>`
            ).join('\n            ')}
        </ul>
    </nav>
    
    <main>
        <section class="hero">
            <h2>Welcome to ${title}</h2>
            <p>This is a sample website generated by AI Core.</p>
        </section>
        
        <section class="content">
            <h3>About This Site</h3>
            <p>This ${pageCount}-page website was created automatically. You can customize it by editing the HTML and CSS files.</p>
        </section>
    </main>
    
    <footer>
        <p>&copy; 2024 ${title}. Generated by AI Core.</p>
    </footer>
</body>
</html>`;
  }

  /**
   * Generate additional page
   */
  generatePageHtml(title, pageNum, totalPages) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <nav>
        <h1>My Website</h1>
        <ul>
            <li><a href="index.html">Home</a></li>
            ${Array.from({ length: totalPages - 1 }, (_, i) => 
              `<li><a href="page${i + 2}.html">Page ${i + 2}</a></li>`
            ).join('\n            ')}
        </ul>
    </nav>
    
    <main>
        <section class="hero">
            <h2>${title}</h2>
            <p>This is page ${pageNum} of ${totalPages}.</p>
        </section>
        
        <section class="content">
            <h3>Content Section</h3>
            <p>Add your content here. This page can be customized to suit your needs.</p>
        </section>
    </main>
    
    <footer>
        <p>&copy; 2024 My Website. Generated by AI Core.</p>
    </footer>
</body>
</html>`;
  }

  /**
   * Generate CSS
   */
  generateCSS(theme) {
    return `* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #333;
}

nav {
    background: #2c3e50;
    color: white;
    padding: 1rem 2rem;
}

nav h1 {
    margin-bottom: 0.5rem;
}

nav ul {
    list-style: none;
    display: flex;
    gap: 1.5rem;
}

nav a {
    color: white;
    text-decoration: none;
}

nav a:hover {
    text-decoration: underline;
}

main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

.hero {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 4rem 2rem;
    border-radius: 8px;
    margin-bottom: 2rem;
}

.hero h2 {
    font-size: 2.5rem;
    margin-bottom: 1rem;
}

.content {
    padding: 2rem;
    background: #f8f9fa;
    border-radius: 8px;
}

.content h3 {
    margin-bottom: 1rem;
}

footer {
    background: #2c3e50;
    color: white;
    text-align: center;
    padding: 1rem;
    margin-top: 2rem;
}`;
  }
}

module.exports = CodeTools;
